Overhaul of code style.
- Changed code style to current style.
- Removed unnecessary functions and lines
- Updated README

diff --git a/cpu b/cpu
--- a/cpu
+++ b/cpu
@@ -1,164 +1,108 @@
 #!/bin/bash
-## 
-## CONTRIBUTORS: 
-## 
-##     * Gabriel Gonzalez (gabeg@bu.edu) 
-## 
-## 
-## LICENSE: 
-## 
-##     The MIT License (MIT)
-## 
-## 
-## NAME:
-## 
-##     cpu - Display CPU information.
-## 
-## 
-## SYNTAX: 
-## 
-##     cpu [-i] [-d]
-## 
-## 
-## PURPOSE:
-## 
-##     Display information on the computer CPU usage and architecture.
-## 
-## 
-## OPTIONS:
-## 
-##     -i, --info
-##         Displays extra CPU information.
-## 
-##     -d, --display
-##         Display a GUI noification, using "noti", that shows the CPU usage.
-## 
-## 
-## FUNCTIONS:
-## 
-##     print_usage - Print program usage.
-## 
-##     print_cpu   - Print CPU usage.
-## 
-##     gui_display - Display CPU usage using the GUI.
-## 
-## 
-## FILE STRUCTURE:
-## 
-##     * Print Program Usage
-##     * Print CPU Usage
-##     * GUI CPU Notification
-##     * Display CPU Information
-## 
-## 
-## MODIFICATION HISTORY:
-## 	
-##     gabeg Dec 19 2014 <> Created.
-## 
-##     gabeg Jan 07 2015 <> Added the GUI notification display.
-## 
-## **********************************************************************************
+# ******************************************************************************
+# 
+# Name:    cpustat
+# Author:  Gabriel Gonzalez
+# Email:   gabeg@bu.edu
+# License: The MIT License (MIT)
+# 
+# Syntax: cpustat [options]
+# 
+# Description: Display CPU information, such as architecture and usage.
+# 
+# Notes: None.
+# 
+# ******************************************************************************
 
+# Globals
+PROG=`basename $0`
 
+# Source utility
+. ../lib/util.sh
 
-## ================
-## GLOBAL VARIABLES
-## ================
+# Exit statuses
+STATUS_NORMAL=0
+STATUS_GETOPT=1
 
-## Program information
-ARGV=("$@")
-PROG_NAME=`basename $0`
+# ******************************************************************************
+# Main
+main()
+{
+    [ $# -eq 0 ] && usage && exit ${STATUS_NORMAL}
 
-## Gui notification bubble
-NOTIFY="noti"
-NOTIFY_PATH=`hash "${NOTIFY}" 2>&1`
+    short="hui"
+    long="help,usage,info"
+    args=$(getopt -o "${short}" --long "${long}" --name "${PROG}" -- "${@}")
 
+    [ $? -ne 0 ] && usage && exit ${STATUS_GETOPT}
+    eval set -- "${args}"
 
+    # Parse options
+    while true; do
+        case "${1}" in
+            # Print program usage
+            -h|--help) 
+                usage
+                ;;
 
-## ###############################
-## ##### PRINT PROGRAM USAGE #####
-## ###############################
+            # Print CPU usage
+            -u|--usage)
+                print_cpu_usage
+                ;;
 
-## Print program usage
-function print_usage {
-    echo "Usage: ${PROG_NAME} [-i]"
-    exit 1
-}
+            # Print CPU information
+            -i|--info)
+                print_cpu_info
+                ;;
 
-
-
-## ###########################
-## ##### PRINT CPU USAGE #####
-## ###########################
-
-## Print CPU usage
-function print_cpu {
-    
-    ## Determine CPU usage
-    local all_cpu_used=(`mpstat -P ALL | tail -4 | awk ' { print 100 - $13 } '`)
-    
-    local i=0
-    for cpu in "${all_cpu_used[@]}"; do
-        echo "CPU ${i}: ${cpu}%"
-        i=$[ $i + 1 ]
+            # End of options
+            --)
+                break
+                ;;
+        esac
+        shift
     done
 }
 
-
-
-## ####################################
-## ##### GUI BATTERY NOTIFICATION #####
-## ####################################
-
-## GUI notification for battery information
-function gui_display {
-    
-    ## Check if notification program exists
-    if [ ! -z "${NOTIFY_PATH}" ]; then 
-        echo "${PROG_NAME}: '${NOTIFY}' does not exist."
-        exit 1
-    fi
-    
-    ## Display current battery level
-    ${NOTIFY} --time 5 -b "$(print_cpu)" 
+# ******************************************************************************
+# Print program usage
+usage()
+{
+    echo "Usage ${PROG} [options]"
+    echo 
+    echo "Options:"
+    echo "    -h, --help"
+    echo "        Print program usage."
+    echo
+    echo "    -u, --usage"
+    echo "        Print CPU usage for all CPUs."
+    echo
+    echo "    -i, --info"
+    echo "        Print CPU information."
 }
 
-
-
-## ###################################
-## ##### DISPLAY CPU INFORMATION #####
-## ###################################
-
-## Print CPU information
-function main {
-    
-    
-    ## Print CPU information
-    case "${ARGV[0]}" in
-        "") 
-            print_cpu
-            ;;
-        
-        "-i"|"--info")
-            
-            ## Check if CPU architecture command exists
-            lsc_prog=`hash lscpu 2>&1`
-            if [ -z "${lsc_prog}" ]; then
-                lscpu
-            fi
-            ;;
-        
-        "-d"|"--display")
-            gui_display
-            ;;
-        
-        *)
-            print_usage
-            ;;
-    esac
+# ******************************************************************************
+# Print CPU usage
+print_cpu_usage()
+{
+    local allcpus=($(mpstat -P ALL | awk ' { print 100 - $13 } '))
+    local line=0
+    for cpu in "${allcpus[@]}"; do
+        line=$[ ${line} + 1 ]
+        if [ ${line} -lt 5 ]; then
+            continue
+        fi
+        echo "CPU $[ ${line} - 5 ]: ${cpu}%"
+    done
 }
 
+# ******************************************************************************
+# Print CPU information
+print_cpu_info()
+{
+    lscpu
+}
 
-
-## Execute main
-main 
+# ******************************************************************************
+# Run script
+main "${@}"
